version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - run:
          name: Print versions
          command: |
            node -v
            npm -v

      - checkout

      - restore_cache:
          name: Restoring NPM Cache
          keys:
            - npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v1-master
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          name: Saving NPM Cache
          key: npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm

      - run:
          name: TypeCheck
          command: npm run check
      - run:
          name: LintCheck
          command: npm run lint -- --format junit -o reports/eslint/report.xml
      - run:
          name: TestCheck
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit --collectCoverage --verbose
          environment:
            JEST_JUNIT_OUTPUT: "reports/jest/report.xml"

      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: coverage
